### ISSUE TITLE
What we think we will be doing

### ISSUE THREAD

**Issue by GillianYue** [Carol-and-Gillian/online-inventory#2]
Talk about the big picture of what we will be working on and how the desired functions will be achieved

**Comment by GillianYue** [comment]
The website will be written in HTML 5, and according to Carol we can use external CSS in HTML  for styling of the website, and Javascript/PHP for programming the behavior of the website. We decided that we will have a general presentation of the several big sections of the store on the main page, and each section (e.g. snacks) is a child of the main page. Under each child section page, the items belonging to that section will be listed and shown. We also think that we'll need an online database for data storage, so more research on how to incorporate that into the structure is needed.

**Comment by GillianYue** [comment]
3d modeling will happen after we have the main structure of the website done. For now, i think we can use images as placeholders

**Comment by flandre17** [comment]
We designed the layouts for the main page and the sub pages of our web app; we also thought about some main methods we will use in our project.
