### ISSUE TITLE
Sections listed in Carousel

### ISSUE THREAD

**Issue by GillianYue** [Carol-and-Gillian/online-inventory#4]
Carousel displays preliminary imgs for each of the five big sections of products bookstore sells. Carousel also has title, small paragraph and a button on each slide. Our goal is to make the img itself the button, instead of having a separate one. Also, when we get to 3d modeling, the preliminary imgs will be replaced, ideally, by the models we create.

**Comment by flandre17** [comment]
Finished five categories in the carousel
